### ISSUE TITLE
all data gets flagged when using an unpolarized calibrator as a polcal and crosscal_polarisation_angle=True

### ISSUE THREAD

**Issue by radiodlucero** [apertif/apercal#104]
This is a reminder for Tammo Jan

All data gets flagged when using an unpolarized calibrator as a polcal and crosscal_polarisation_angle=True

We may either want to:
(1) set this parameter to False as a default in the default.cfg
(2) leave it set to True and put a warning somewhere in the .cfg or notebooks that this should be set to False when no proper polcal is available.  
(3) Put this in other document describing the pipeline so it is easy to reference.

A polcal should always be observed during the surveys at which time this will not be an issue except we need to be sure we set the correct calibrator as the polcal.

**Comment by tammojan** [comment]
Assuming yes here.

**Comment by radiodlucero** [comment]
I think you could since there are really only two, 3C138 and 3C286.
