### ISSUE TITLE
scal step create 65 GB temporary file for a  80 MB datset

### ISSUE THREAD

**Issue by gijzelaerr** [apertif/apercal#144]
the invert command:
```
invert map=map slop=1 beam=beam stokes=i cell=5 vis=/ctEBeh/NGC807.mir imsize=1024 
````
creates a 65 GB map folder.
```
λ  du -skh *
4,1M    beam
65G     map
80M     NGC807.mir
```

**Comment by adebahr** [comment]
Selfcal creates a small cube to find RFI/HI-emission for flagging. This file can easily be moved to another folder, but is anyhow removed after the step. Is it a problem if we create it in the tempdir?
