### ISSUE TITLE
clean does not work with given starting model

### ISSUE THREAD

**Issue by adebahr** [apertif/apercal#157]
I get the following error when running the clean task in MIRIAD:
```
(pipeline) adebahr@happili-01:/data/adebahr/apertif/scal_test/00/continuum$ clean cutoff=0.0006072916463017464 map=map_C00_00 region="mask(mask_C00_01)" beam=beam_C00_00 niters=1000000 model=model_C00_00 out=model_C00_01 

clean: Revision 1.16, 2018/11/29 23:30:11 UTC

Subtracting initial model ...
Begin iterating

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7F91BBF76E08
#1  0x7F91BBF75F90
#2  0x7F91BB6984AF
#3  0x4033B8
#4  0x403E22
#5  0x405F9A
#6  0x406795
#7  0x7F91BB68382F
#8  0x402468
#9  0xFFFFFFFFFFFFFFFF
Segmentation fault (core dumped)
```

This looks very similar to the problem we encountered after recompiling with the mfclean task. Maybe there is a bug in the code here as well?

**Comment by vdhulst** [comment]
does this error also occur with the old miriad? (activate via: source /home/apercal/oldmiriad).

**Comment by adebahr** [comment]
No it doesn't. It works with the old MIRIAD:

(pipeline) adebahr@happili-01:/data/adebahr/apertif/scal_test/00/continuum$ clean cutoff=0.0006072916463017464 map=map_C00_00 region="mask(mask_C00_01)" beam=beam_C00_00 niters=1000000 model=model_C00_00 out=model_C00_01 

clean: Revision 1.14, 2015/10/29 01:31:02 UTC

Subtracting initial model ...
Begin iterating
 Clark  Iterations: 38
 Residual min,max,rms:   -6.363E-04   4.041E-03   2.069E-03
 Total CLEANed flux:    1.645E-01
 Clark  Iterations: 449
 Residual min,max,rms:   -4.541E-04   5.311E-04   2.503E-04
 Total CLEANed flux:    1.798E-01
 Stopping -- Clean cutoff limit reached

**Comment by vdhulst** [comment]
OK, thanks. I will document it and hand it over to Mark Wieringa for information and debugging. As the weekend has started in Sydney I do not expect an answer until early next week.

**Comment by vdhulst** [comment]
@adebahr: Mark Wieringa responded today and found another bug. This one was more tricky he said. I recompiled clean and it works now in the new installation. Mark is thankful to you for finding them.
