### ISSUE TITLE
Target/calibrator observations on different dates

### ISSUE THREAD

**Issue by eakadams** [apertif/apercal#168]
apercal.prepare only accepts one date, but target and calibrator observations may start on different dates. The functionality needs to allow copying a connected set of observations that have different dates.

Note that I tried to run apercal.prepare for just the target and one calibrator (other had a separate date) but wasn't able to leave the obsnum field set to None or '' without getting an error.

**Comment by tammojan** [comment]
Actually the prepare step is a very involved wrapper arount getdata_alta. The best fix is to just iterate over beams yourself. Or you can use the start_apercal_pipeline to do a simple loop for you, as for example in `~dijkema/apercal_manual`, or below:
```
from apercal.pipeline import start_apercal_pipeline
hostnum = int(os.uname()[1].split('-')[-1])
my_beamnums = list(range(10*(hostnum-1), 10*hostnum))

cal_obsids = list(range(190309042, 190309070)+range(190310001, 190310013))
assert(len(cal_obsids)==40)

# Make a list of (obsid, name, beamnr) tuples
my_cals = [(cal_obsids[beamnr], "3C286", beamnr) for beamnr in my_beamnums]
my_pols = None

obsid_target, targetname = 190308083, '3C147_drift'
start_apercal_pipeline((obsid_target, targetname, my_beamnums), my_cals, my_pols, steps=["prepare"])
```
