### ISSUE TITLE
create mock up of ideas for GUI

### ISSUE THREAD

**Issue by gijzelaerr** [apertif/apercal#30]

**Comment by tammojan** [comment]
![mockup-status](https://user-images.githubusercontent.com/7974906/47496576-8a5e7280-d857-11e8-9e37-c104565ff46d.png)

See above. Basically, observations can be expanded into the 'beams' (2 calibrators, something like 40 targets) that constitute an observation. Each beam has a progress indicator showing which steps are done. Green=done, yellow=running, red=failed. Clicking on a green/red/yellow cell takes you to a log or a page with a log and intermediate results.

I think this is more or less what you were showing, except with the added logic about observation + beams. Presenting this in a scatter dependency graph is I think less useful.

**Comment by gijzelaerr** [comment]
Not sure if this is going to make it in the current Buis, maybe in a future release.
