### ISSUE TITLE
Enable travis

### ISSUE THREAD

**Issue by gijzelaerr** [apertif/apercal#31]
i've made a docker + travis setup that will run the integration test suite and do a pep8 check on the code.

https://github.com/apertif/apercal/blob/cwl/.travis.yml

the code is looking already much better, but there are still many warnings.

**Comment by gijzelaerr** [comment]
I dont have access to do this so tammo-jan should.

**Comment by tammojan** [comment]
Should be enabled now; a commit on the `cwl` branch should trigger a build.
