### ISSUE TITLE
debug TravisCI hang during the package installation

### ISSUE THREAD

**Issue by mr-c** [apertif/apercal#35]
For @gijzelaerr

**Comment by gijzelaerr** [comment]
there were multiuple problems, but it looks like travis is having difficulties installing the CASA debian package, it just takes too long to download. I'm making a CASA docker image, which is just KERN-dev with CASA preinstalled. lets see if that works better.

**Comment by gijzelaerr** [comment]
i think it is fixed in this PR https://github.com/apertif/apercal/pull/41 https://travis-ci.org/apertif/apercal/builds/449837218

The tests and pep8 are still failing though

**Comment by tammojan** [comment]
The travis you link to fails on getting the data, not the tests.

**Comment by gijzelaerr** [comment]
oops sorry, fixed. afaik the latest master is running the test suite!
