### ISSUE TITLE
Install aoflagger in travis

### ISSUE THREAD

**Issue by tammojan** [apertif/apercal#52]
We need an unreleased version of aoflagger unfortunately.

**Comment by tammojan** [comment]
Perhaps @aroffringa can make a release of AOFlagger that includes the bandpass correction option?

**Comment by gijzelaerr** [comment]
but yes a new release of aoflagger would be the easiest, I then update it in KERN-dev.

**Comment by aroffringa** [comment]
I've released aoflagger 2.13 that includes the bandpass correction option.

**Comment by gijzelaerr** [comment]
uploaded 2.13 to KERN-dev, so that should be picked up by the container builds on travis from now on.
