### ISSUE TITLE
CWL fails when writable input directory contains new subfolders

### ISSUE THREAD

**Issue by gijzelaerr** [apertif/apercal#63]
Unhandled error, try again with --debug for more information:
  [Errno 2] No such file or directory: '/home/gijs/Work/apercal/cwl/outdir/NGC807.MS/APERTIF_CALIBRATION/table.f1'

full debug log : https://gist.github.com/gijzelaerr/b67c19669a5ee2b5d0c8c762607bf879

**Comment by mr-c** [comment]
Is `table.f1` or `APERTIF_CALIBRATION` a new subfolder, or was a folder deleted?

**Comment by mr-c** [comment]
Looks like `/home/gijs/Work/apercal/data/small/00/raw/NGC807.MS/APERTIF_CALIBRATION/table.f` was deleted, and this upset `cwltool`. This is a bug, writable Files may indeed be deleted.

**Comment by gijzelaerr** [comment]
but that is weird since, as, far as I know, `APERTIF_CALIBRATION` is created by our pipeline... Right @tammojan ?

**Comment by gijzelaerr** [comment]
the `cwltool --no-compute-checksum` workaround works!

I just ran this on OSX with Docker, so that seems to be working also.

**Comment by gijzelaerr** [comment]
this issue seems to be resolved
