### ISSUE TITLE
Set miriad env in container

### ISSUE THREAD

**Issue by tammojan** [apertif/apercal#65]
Miriad needs some environment variables to run properly. Not sure where to set these: in the Dockerfile, in the kern package, or in the pipeline. Typically, the file `MIRRC.sh` needs to be sourced before startup. This sets a lot of environment variables.

**Comment by gijzelaerr** [comment]
this is happening now right?

https://github.com/apertif/apercal/blob/master/Dockerfile#L17

**Comment by tammojan** [comment]
Yes this happens now.
