### ISSUE TITLE
Setjy out of order in crosscal

### ISSUE THREAD

**Issue by radiodlucero** [apertif/apercal#83]
Setjy should be done for all calibrators at the beginning of the crosscal module.  

In the cross calibration module all setjy calls for all calibrators currently comes after the first gaincal and the bandpass calibration.  This causes an incorrect slope in the calibrated data.

**Comment by radiodlucero** [comment]
Hi Tammo Jan,

I went ahead and fixed this issue.  However, I am not familiar with how to put it on the github so that it can be properly merged into the master branch.  I attached the new ccal.py file here which fixes the above issue.  I had to change it to a .txt file to upload it here.  Apparently .py files are not supported.  
[ccal.txt](https://github.com/apertif/apercal/files/2626301/ccal.txt)

**Comment by tammojan** [comment]
Thanks for fixing this Danielle! Could you have a look at #86, in particular at the diff (click commits) to see if this indeed the change you want to make? In particular, be very cautious if the indentation.
